repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: check-yaml
        files: .*\.(yaml|yml)$

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
        files: ^src/|tests/

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy src
        language: system
        pass_filenames: false

-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        files: ^src/
        types: [python]
        exclude_types: [xml, wtf]
        language: system

-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8 src
        language: system
        pass_filenames: false

-   repo: local
    hooks:
    -   id: tests
        name: Tests
        entry: pytest
        language: system
        stages: [push]
        pass_filenames: false
