repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    # Disabling trailing-whitespace because we can't have our test data files modified
    # -   id: trailing-whitespace
    # Ditto for the end-of-file fixer
    # -   id: end-of-file-fixer
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: check-yaml
        files: .*\.(yaml|yml)$

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
        files: ^src/|tests/

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy src
        language: system
        pass_filenames: false

# Black: thanks, I hate it.
# -   repo: local
#     hooks:
#     -   id: black
#         name: black
#         entry: black
#         files: ^src/|tests/
#         language: system

-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8 src
        language: system
        pass_filenames: false

-   repo: local
    hooks:
    -   id: tests
        name: Tests
        entry: pytest
        language: system
        stages: [push]
        pass_filenames: false

-   repo: https://github.com/NASA-AMMOS/slim-detect-secrets
    # using commit id for now, will change to tag when official version is released
    rev: 91e097ad4559ae6ab785c883dc5ed989202c7fbe
    hooks:
      - id: detect-secrets
        args:
          - '--baseline'
          - '.secrets.baseline'
          - --exclude-files '\.secrets..*'
          - --exclude-files '\.pre-commit-config.yaml'
          - --exclude-files '\.git.*'
          - --exclude-files '\.mypy_cache'
          - --exclude-files '\.pytest_cache'
          - --exclude-files '\.tox'
          - --exclude-files '\.venv'
          - --exclude-files 'venv'
          - --exclude-files 'dist'
          - --exclude-files 'build'
          - --exclude-files '.*\.egg-info'
