[build-system]
requires = ["setuptools >= 46.4.0", "wheel"]
build-backend = "setuptools.build_meta"


# This is kept for posterity; `black` is not used in this repository
[tool.black]
line-length = 120
